name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: ${{ matrix.os }} ${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            python: "3.9"
            #start_worker: "docker run -di -v ${WORKSPACE}:${WORKSPACE} -v ${GITHUB_ENV}:${GITHUB_ENV} -w ${WORKSPACE} --name worker --rm quay.io/pypa/manylinux2010_x86_64"
            #worker: "docker exec -e GITHUB_ENV=${GITHUB_ENV} worker"
            #stop_worker: "docker kill worker"
            container: quay.io/pypa/manylinux2010_x86_64
          - os: "macos-latest"
            python: "3.9"
          - os: "windows-latest"
            python: 3.9
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
      WORKSPACE: "${{ github.workspace }}"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      - name: Start the worker
        run: ${{ matrix.start_worker }}
      - name: Python version
        run: ${{ matrix.worker }} python --version
      - name: Set up Python
        run: ${{ matrix.worker }} python .ci/wheels/setup_python.py ${{ matrix.python }}
      - name: Show env file
        run: cat $GITHUB_ENV
        if: ${{ matrix.os != 'windows-latest' }}
      - name: Run Python
        run: ${{ matrix.worker }} ${{ env.PYTHON }} --version
      - name: Stop the worker
        run: ${{ matrix.stop_worker }}
