name: Build FooBar
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
      - name: Build
        shell: cmd
        run: call .\.ci\windows\build.cmd
