name: Build FooBar
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lamyj/dicomifier
      - run: ./tests/download_data
      - uses: actions/upload-artifact@v2
        with:
          name: test-data
          path: |
            tests/data/input
            tests/data/baseline
  build:
    needs: fetch
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2 # TODO
        with:
          name: test-data
      - run: ls -l tests/data/*
      
