name: Build wheels (manylinux)
on: [push, create]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: "macos-10.15", name: "3.8" }
          - { os: "macos-10.15", name: "3.9" }
          - { os: "ubuntu-20.04", name: "3.8" }
          - { os: "ubuntu-20.04", name: "3.9" }
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Provision environment
        run: |
          PYTHON_ROOT=$(python3 ./.ci/wheels/setup_python.py '${{ matrix.name }}' | tail -n 1)
          echo "PYTHON_ROOT=$PYTHON_ROOT" >> $GITHUB_ENV
      - name: Python
        run: |
          echo "Python root: $PYTHON_ROOT"
          ls $PYTHON_ROOT
          $PYTHON_ROOT/bin/python --version
          $PYTHON_ROOT/bin/pip
