name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
          - os: "macos-latest"
          - os: "windows-latest"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      - name: Set-up Python
        run: python3 --version
      - name: Install cmake
        shell: python
        run: |
          import io
          import os
          import site
          import subprocess
          import sys
          import tempfile
          import urllib.request
          import zipfile

          subprocess.check_call([
              sys.executable, "-m", "pip", "install", "--force-reinstall", "pip"])

          subprocess.check_call([
              sys.executable, "-m", "pip", "install", "--user", 
              "setuptools", "wheel", "setuptools_scm", "cibuildwheel",
              "cmake", "pybind11"])

          os.environ["PATH"] = os.pathsep.join([
              os.environ["PATH"], 
              os.path.join(site.USER_BASE, "bin"),
              os.path.join(site.USER_SITE, "../Scripts")])

          with tempfile.TemporaryDirectory() as directory:
              with urllib.request.urlopen("https://github.com/xtensor-stack/xsimd/archive/refs/tags/7.5.0.zip") as fd:
                  archive = zipfile.ZipFile(io.BytesIO(fd.read()))
                  archive.extractall(directory)
              subprocess.check_call(
                  [
                      "cmake", 
                      "-DCMAKE_INSTALL_PREFIX={}".format(
                          os.path.join(site.USER_BASE, "include")), 
                      "."], 
                  cwd=os.path.join(directory, "xsimd-7.5.0"))
              subprocess.check_call(
                  ["cmake", "--build", ".", "--config", "Release", "--target", "install"],
                  cwd=os.path.join(directory, "xsimd-7.5.0"))
