name: Build FooBar
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lamyj/dicomifier
      - run: curl -L -o dicomifier-data.zip --silent --show-error https://iris.icube.unistra.fr/nextcloud/s/qGD3XgXoLbF9D8w/download
      - run: ls -l
      - uses: actions/upload-artifact@v2
        with:
          name: test-data
          path: |
            dicomifier-data.zip
  build:
    needs: fetch
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-10.15
    steps:
      # FIXME? this is already done in the first action. Add to artifact?
      - run: ls -l
      - uses: actions/checkout@v2
        with:
          repository: lamyj/dicomifier
      - run: ls -l
      - uses: actions/download-artifact@v2
        with:
          name: test-data
      - run: ls -l
      
