name: Build FooBar
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    steps:
      - name: Configure environment
        shell: cmd
        # $Env:
        run: |
          echo "WORKSPACE=%GITHUB_WORKSPACE%" >> %GITHUB_ENV%
          echo "PYTHON=${{ matrix.python }}" >> %GITHUB_ENV%
          echo "CMAKE_OPTIONS=${{ matrix.cmake_options }}" >> %GITHUB_ENV%
      - name: Clone source
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
      - name: Setup conda
        #uses: s-weigand/setup-conda@v1.0.5
        shell: cmd
        run: |
          C:\Miniconda\condabin\conda.bat init
      - name: Build
        # shell: bash
        shell: cmd
        # Get-ChildItem -Path Env:\
        run: |
          C:\Miniconda\condabin\conda.bat activate base
          C:\Miniconda\condabin\conda.bat install --yes -c conda-forge boost cmake ninja numpy pybind11 xsimd
          set
          .ci\windows\build.cmd
