name: Build FooBar
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          conda-channels: anaconda, conda-forge
      - run: conda install xsimd
      - run: conda install sycomore
