name: Build wheels (manylinux)
on: [push, create]

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Python 3.8", python: /opt/python/cp38-cp38/bin/python, tag: 2010 }
          - { name: "Python 3.9", python: /opt/python/cp39-cp39/bin/python, tag: 2010 }
    env:
      WORKSPACE: "${{ github.workspace }}"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Start the worker
        run: |
          docker run -di -v ${WORKSPACE}:${WORKSPACE} --name worker --rm quay.io/pypa/manylinux${{ matrix.tag }}_x86_64:latest
      - name: Provision environment
        run: |
          docker exec -w ${WORKSPACE} worker ./.ci/wheels/provision.sh
      - name: Build wheel
        run: |
          docker exec -w ${WORKSPACE} worker ${{ matrix.python }} setup.py bdist_wheel
      - name: Test the package
        run: |
          docker exec -w ${WORKSPACE} worker ${{ matrix.python }} -m pip install dist/*whl
          docker exec -w ${WORKSPACE} worker ${{ matrix.python }} -c 'import sycomore; sycomore.gamma'
      - name: Stop the worker
        run: docker kill worker
      - name: Archive wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist/*whl
