name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
          - os: "macos-latest"
          - os: "windows-latest"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install cmake
        shell: python
        run: |
          import os
          import site
          import subprocess
          import sys
          print(sys.version, sys.executable, site.USER_BASE)
          # Add site.USER_BASE/bin and site.USER_SITE/../Scripts to PATH
          os.environ.update({
            "PATH": os.pathsep.join([
              os.environ["PATH"], 
                os.path.join(site.USER_BASE, "bin"),
                os.path.join(site.USER_SITE, "../Scripts")])})
          subprocess.check_call([sys.executable, "-m", "pip", "install", "--user", "cmake"])
          subprocess.check_call([sys.executable, "-m", "pip", "show", "--files", "cmake"])
          subprocess.check_call([os.path.join("cmake", "--version")])
