name: Build wheels (manylinux)
on: [push, create]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-10.15]
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Build wheels
        uses: joerick/cibuildwheel@v1.11.0
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value



