name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: ${{ matrix.container || matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { os: ubuntu-latest, ci_type: deb, container: debian:stretch, python: python3 }
          - { os: "ubuntu-latest", ci_type: "deb", container: "debian:buster", python: "python3" }
          - os: macos-10.15
            ci_type: brew
            python: python3
            # cmake_options: "-DPYTHON_EXECUTABLE=/usr/local/bin/python3"
          - { os: "windows-latest", ci_type: "windows", python: "python" }
          # FIXME: sample wheels?
    env:
      WORKSPACE: "${{ github.workspace }}"
      PYTHON: "${{ matrix.python }}"
      CMAKE_OPTIONS: "${{ matrix.cmake_options }}"
    
    steps:
      # Windows-specific steps
      - name: Setup conda
        if: ${{ contains(matrix.os, 'windows') }}
        run: C:\Miniconda\condabin\conda.bat init powershell
      - name: Set up dev environment
        if: ${{ contains(matrix.os, 'windows') }}
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      # Debian/Ubuntu-specific steps
      - name: Install Git and Python
        run: apt-get update && apt-get install -y git python3
        if: ${{ contains(matrix.container, 'debian') || contains(matrix.container, 'ubuntu') }}
      # Generic steps
      - name: Checkout latest revision
        run: git clone https://github.com/lamyj/sycomore.git .
      # Use it as sys.executable to feed to CMake PYTHON_EXECUTABLE
      - name: Built-in Python version
        run: ${{ matrix.python }} -V
      # - name: Configure the build
      #   run: ./.ci/${{ matrix.ci_type}}/install
      # - name: Build Sycomore
      #   # Differences between brew and deb: -DCMAKE_CXX_FLAGS="-march=native -ffast-math" in brew, nothing in deb
      #   # Differences between windows and deb: "--config Release" and generator (nothing vs ninja)
      #   run: ./.ci/${{ matrix.ci_type}}/build
      # - name: Run tests
      #   # Differences between brew and deb: DYLD_LIBRARY_PATH vs LD_LIBRARY_PATH
      #   # Differences between windows and deb: LD_LIBRARY_PATH
      #   run: ./.ci/${{ matrix.ci_type}}/post_build
