name: Build FooBar
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    steps:
      - name: Clone source
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
      - name: Setup conda
        uses: s-weigand/setup-conda@v1.0.5
      - name: Build
        shell: bash
        run: |
          conda install --yes -c conda-forge cmake ninja numpy pybind11 xsimd
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release ../
