name: Build FooBar
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: lamyj/dicomifier
      - run: ./tests/download_data
      - run: ls tests/data
      - uses: actions/upload-artifact@v2
        with:
          name: test-data
          path: |
            tests/data/input
            tests/data/baseline
  build:
    needs: fetch
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-10.15
    steps:
      # FIXME? this is already done in the first action. Add to artifact?
      - uses: actions/checkout@v2
        with:
          repository: lamyj/dicomifier
      - uses: actions/download-artifact@v2
        with:
          name: test-data
      - run: ls -l tests/data/*
      
