name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: ${{ matrix.os }} ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # FIXME? test wheel CI on min python version
          # FIXME? test wheel CI on max python version
          - os: ubuntu-latest
            ci_type: deb
            container: debian:stretch
            python: python3
          - os: ubuntu-latest
            ci_type: deb
            container: debian:buster
            python: python3
          - os: macos-10.15
            ci_type: brew
            python: /usr/local/bin/python3
            cmake_options: "-DPYTHON_EXECUTABLE=/usr/local/bin/python3"
          - os: windows-latest
            ci_type: windows
            python: python
    
    env:
      WORKSPACE: "${{ github.workspace }}"
      PYTHON: "${{ matrix.python }}"
      CMAKE_OPTIONS: "${{ matrix.cmake_options }}"
    
    steps:
      # Windows-specific steps
      - name: Setup conda
        if: ${{ contains(matrix.os, 'windows') }}
        run: C:\Miniconda\condabin\conda.bat init powershell
      - name: Set up dev environment
        if: ${{ contains(matrix.os, 'windows') }}
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      # Generic steps
      - name: Checkout latest revision
        run: git clone https://github.com/lamyj/sycomore.git .
      - name: Configure the build
        run: ./.ci/${{ matrix.ci_type}}/install
      - name: Build Sycomore
        run: ./.ci/${{ matrix.ci_type}}/build
      - name: Run tests
        run: ./.ci/${{ matrix.ci_type}}/post_build
