name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
          - os: "macos-latest"
          - os: "windows-latest"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install cmake
        shell: python
        run: |
          import os
          import site
          import subprocess
          import sys
          
          subprocess.check_call([
              sys.executable, "-m", "pip", "install", "--force-reinstall", "pip"])
          
          subprocess.check_call([
              sys.executable, "-m", "pip", "install", "--user", 
              "setuptools", "wheel", "setuptools_scm",
              "cmake", "pybind11"])
          
          subprocess.check_call([
              sys.executable, "-m", "pip", "show", "--files", "pybind11"])
          
          os.environ["PATH"] = os.pathsep.join([
              os.environ["PATH"], 
              os.path.join(site.USER_BASE, "bin"),
              os.path.join(site.USER_SITE, "../Scripts")])
              
          #subprocess.check_call(["cmake", "--version"], env=os.environ)
          #subprocess.check_call(["cmake", "--version"])
