name: Build wheels (manylinux)
on: [push, create]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "3.8"
            os: "ubuntu-latest"
            start_worker: "docker run -di -v ${WORKSPACE}:${WORKSPACE} --name worker --rm quay.io/pypa/manylinux2010_x86_64"
            worker: "docker exec worker"
            stop_worker: "docker kill worker"
          - name: "3.9"
            os: "ubuntu-latest"
            start_worker: "docker run -di -v ${WORKSPACE}:${WORKSPACE} --name worker --rm quay.io/pypa/manylinux2010_x86_64"
            worker: "docker exec worker"
            stop_worker: "docker kill worker"
          - name: "3.8"
            os: "macos-latest"
          - name: "3.9"
            os: "macos-latest"
    env:
      MACOSX_DEPLOYMENT_TARGET: "10.9"
      WORKSPACE: "${{ github.workspace }}"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Start the worker
        run: ${{ matrix.start_worker }}
      - name: Configure Python interpreter
        run: |
          PYTHON_ROOT=$(python3 ./.ci/wheels/setup_python.py '${{ matrix.name }}' | tail -n 1)
          echo "PYTHON_ROOT=$PYTHON_ROOT" >> $GITHUB_ENV
      - name: Python
        run: |
          echo "Python root: $PYTHON_ROOT"
          ${{ matrix.worker }} ls $PYTHON_ROOT
          ${{ matrix.worker }} $PYTHON_ROOT/python --version
          ${{ matrix.worker }} $PYTHON_ROOT/pip
      - name: Stop the worker
        run: ${{ matrix.stop_worker }}
