name: Build FooBar
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
    steps:
      - name: Configure environment
        # shell: bash
        run: |
          echo "WORKSPACE=${GITHUB_WORKSPACE}" >> $Env:GITHUB_ENV
          echo "PYTHON=${{ matrix.python }}" >> $Env:GITHUB_ENV
          echo "CMAKE_OPTIONS=${{ matrix.cmake_options }}" >> $Env:GITHUB_ENV
      - name: Clone source
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
      - name: Setup conda
        #uses: s-weigand/setup-conda@v1.0.5
        # shell: cmd
        run: |
          C:\Miniconda\condabin\conda.bat init powershell
      - name: Build
        # shell: bash
        # shell: cmd
        run: |
          C:\Miniconda\condabin\conda.bat activate base
          C:\Miniconda\condabin\conda.bat install --yes -c conda-forge boost cmake ninja numpy pybind11 xsimd
          Get-ChildItem -Path Env:\
          .ci\windows\build.cmd
