name: Build wheels (manylinux)
on: [push, create]

jobs:
  build:
    runs-on: macos-10.15
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "Python 3.8", python: cp38 }
          - { name: "Python 3.9", python: cp39 }
    env:
      WORKSPACE: "${{ github.workspace }}"
      MACOSX_DEPLOYMENT_TARGET: "10.9"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      - name: Get cibuildwheel
        run: python3 -m pip install cibuildwheel
      - name: Provision environment
        run: ./.ci/wheels/provision.sh
      - name: Build wheel
        run: python3 ./.ci/wheels/build.py '${{ matrix.python }}*'
