name: Build FooBar
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: "Debian 9 (Stretch)"
            os: ubuntu-latest
            ci_type: deb
            start_worker: "docker run -di -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} --name worker --rm debian:stretch"
            worker: "docker exec -w ${GITHUB_WORKSPACE} -e PYTHON=${PYTHON} -e WORKSPACE=${GITHUB_WORKSPACE} worker"
            stop_worker: "docker kill worker"
          - name: "Ubuntu 20.04 (Bionic)"
            os: ubuntu-latest
            ci_type: deb
            start_worker: "docker run -di -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} --name worker --rm ubuntu:bionic"
            worker: "docker exec -w ${GITHUB_WORKSPACE} -e PYTHON=${PYTHON} -e WORKSPACE=${GITHUB_WORKSPACE} worker"
            stop_worker: "docker kill worker"
          - name: "macOS 10.15 (Catalina)"
            os: macos-10.15
            ci_type: brew
            start_worker: ""
            worker: ""
            stop_worker: ""
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
      - run: echo "WORKSPACE=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
      - run: echo $GITHUB_ENV
      - run: echo ${WORKSPACE}
      # - name: Start the worker
      #   run: ${{ matrix.start_worker }}
      # - name: Configure
      #   run: ${{ matrix.worker }} cat /etc/os-release || echo "something went wrong"
      # - name: Stop the worker
      #   run: ${{ matrix.stop_worker }}
