name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
          - os: "macos-latest"
          - os: "windows-latest"
    steps:
      - name: Checkout latest revision
        uses: actions/checkout@v2
        with:
          repository: lamyj/sycomore
          fetch-depth: 0
      # - name: Set up Python
      #   uses: actions/setup-python@v2
      - name: Set-up Python
        run: |
          python3 -m pip install cibuildwheel
          python3 .ci/wheels/setup_python.py 3.9
      
