name: Test
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    name: ${{ matrix.container || matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { os: ubuntu-latest, ci_type: deb, container: debian:stretch, python: python3 }
          - { os: "ubuntu-latest", ci_type: "deb", container: "debian:buster", python: "python3" }
          - { os: "macos-10.15", ci_type: "brew", python: "python3" }
          - { os: "windows-latest", ci_type: "windows", python: "python" }
    env:
      WORKSPACE: "${{ github.workspace }}"
      PYTHON: "${{ matrix.python }}"
    steps:
      # Windows-specific steps
      - name: Setup conda
        if: ${{ contains(matrix.os, 'windows') }}
        run: C:\Miniconda\condabin\conda.bat init powershell
      # Debian/Ubuntu-specific steps
      - name: Install Git and Python
        run: apt-get update && apt-get install -y git python3
        if: ${{ contains(matrix.container, 'debian') || contains(matrix.container, 'ubuntu') }}
      # Generic steps
      - name: Checkout latest revision
        run: git clone https://github.com/lamyj/sycomore.git .
      - name: Configure the build
        run: ./.ci/${{ matrix.ci_type}}/install
      - name: Build sycomore
        run: ${{ matrix.python }} ./.ci/build/build.py
      - name: Run tests
        run: ${{ matrix.python }} ./.ci/build/post_build.py
